 /*
    Siempre se debe definir el paquete
    en el que se encuentra la clase Lexer,
    esto es importante para que el analizador
    lexico pueda encontrar la clase parser.
*/
package com.julian;

// Cup es la clase que contiene los simbolos que
// se usan en el analizador sintactico.
import java_cup.runtime.*;

// Se importa la clase LinkedList para poder usarla en la gramatica.
import java.util.LinkedList;
import com.julian.abstracto.Instruccion;
import com.julian.symbol.*;

// Instrucciones
import com.julian.instruction.Print;

// Expresiones
import com.julian.expresion.Nativo;
import com.julian.expresion.Suma;


/*
    Codigo del parser, se copia integramente a la clase final.
    Agregamos el manejo de errores.
*/
parser code {:

    // Funcion de error posiblemente recuperable
    public void syntax_error(Symbol cur_token) {
        //System.out.println("Error de sintaxis en la linea: " + (s.yyline + 1) + " columna: " + (s.yycolumn + 1));
        System.out.println("Token actual: " + cur_token.value);
        System.out.println("Token esperado: " + cur_token.sym);
        System.out.println("Error recuperable, se intentara recuperar.");
    }

    // Funcion de error No recuperable
    public void unrecovered_syntax_error(Symbol s) {
        // System.out.println("Error de sintaxis en la linea: " + (s.yyline + 1) + " columna: " + (s.yycolumn + 1));
        System.out.println("Token actual: " + cur_token.value);
        System.out.println("Token esperado: " + cur_token.sym);
        System.out.println("Error fatal, no se puede recuperar.");
    }

:}

/*
    El action code funciona como un bloque de codigo que se ejecuta
    antes de que se ejecute la gramatica. En este caso se declara
    una variable de tipo String que se usara para almacenar los
    tokens que se van leyendo.
*/
action code
{:
    String consola = "";
:}

/* ------------Declaracion de simbolos terminales y no terminales---------- */

/* Terminales (tokens obtenidos por el analizador lexico).

   Terminales que no tienen un valor son listados primero, los terminales
   que tienen un valor como los enteros son listados en la segunda o demas
   lineas.
*/

// Terminales que tienen un valor como los enteros son listados
// en la segunda o demas lineas.
terminal String  ID;
terminal String  ENTERO, DECIMAL, BOOLEANO, CADENA, CARACTER;

// Terminales que no tienen un valor son listados primero.
terminal PRINT;
terminal INT, FLOAT, BOOL, CHAR, STRING;
terminal CAST, LET, CONST, AS;
terminal IF, ELSE, MATCH, DEFAULT;
terminal DO, WHILE, FOR, BREAK, CONTINUE;
terminal CONSOLE, LOG;
terminal ADD, SUB, MUL, DIV, POW, ROOT, MOD, USUB;
terminal EQ, NE, LT, LE, GT, GE;
terminal OR, AND, NOT;
terminal LPAREN, RPAREN, LBRACE, RBRACE, SEMICOLON, COLON, DOT;


/* ------------- Sección de no terminales ----------- */

/* No terminales usados en la seccion gramatical.

   Primero se lista los no terminales que tienen un valor Object y despues
   se lista los no terminales que tienen un entero. Un Object se refiere a
   que no tienen tipo, pudiendo ser entero o String.
*/

nonterminal LinkedList<Instruccion> INICIO, INSTRUCCIONES;
nonterminal Instruccion INSTRUCCION, IMPRESION;
nonterminal Instruccion EXPRESION;
//nonterminal Instruccion VALOR;
nonterminal String TIPO;
nonterminal VARIABLES, VARIABLE;

/* ------------- Precedencia y Asociatividad de Terminales ----------- */

/*
   La precedencia de los operadores se define aquí.
   Los operadores en las líneas inferiores tienen mayor precedencia
   que los de las líneas superiores.
*/
precedence right    USUB;
precedence nonassoc POW, ROOT, MOD;
precedence left     MUL, DIV;
precedence left     ADD, SUB;
precedence left     EQ, NE, LT, LE, GT, GE;
precedence right    NOT;
precedence left     AND;
precedence left     OR;

/* ------------------- Sección de la gramática ------------------------ */

// Inicia la gramática con el símbolo de inicio.
/* Símbolo de inicio */
start with INICIO;

/* ------------------- Sección de la gramática ------------------------ */
// ESCRIBIR LA GRAMATICA
INICIO ::= INSTRUCCIONES:a {: RESULT = a; :}
;

INSTRUCCIONES ::= INSTRUCCIONES:a INSTRUCCION:b   {: RESULT = a; RESULT.add(b); :}
                | INSTRUCCION:a                   {: RESULT = new LinkedList<Instruccion>(); RESULT.add(a); :}
;

INSTRUCCION ::= IMPRESION:i SEMICOLON    {: RESULT = i; :}
;

IMPRESION ::= PRINT LPAREN EXPRESION:e RPAREN  {: RESULT = new Print(e, eleft, eright); :}
 //           | PRINT LPAREN STRING:c RPAREN SEMICOLON      {: RESULT = c; :}
;

// public Suma(Instruccion operIzq, Instruccion operDer, int linea, int columna)
EXPRESION ::= // SUB EXPRESION:a                 {: RESULT = -a; :}%prec USUB
            EXPRESION:a ADD EXPRESION:b     {: RESULT = new Suma(a, b, aleft, aright); :}
//            | EXPRESION:a SUB EXPRESION:b     {: RESULT = a - b; :}
//            | EXPRESION:a MUL EXPRESION:b     {: RESULT = a * b; :}
//            | EXPRESION:a DIV EXPRESION:b     {: RESULT = a / b; :}
            | ENTERO:e        {: RESULT = new Nativo(Integer.parseInt(e), new Tipo(tipoDato.ENTERO), eleft, eright); :}
            | DECIMAL:e    {: RESULT = new Nativo(Double.parseDouble(e), new Tipo(tipoDato.DECIMAL), eleft, eright); :}
            | BOOLEANO:e   {: RESULT = new Nativo(Boolean.parseBoolean(e), new Tipo(tipoDato.BOOLEANO), eleft, eright); :}
            | CADENA:e     {: RESULT = new Nativo(e, new Tipo(tipoDato.CADENA), eleft, eright); :}
            | CARACTER:e   {: RESULT = new Nativo(e, new Tipo(tipoDato.CARACTER), eleft, eright); :}
            | LPAREN EXPRESION:e RPAREN       {: RESULT = e; :}
;

// public Nativo(Object valor, Tipo tipo, int linea, int columna)
//
//VALOR ::= NUM:e        {: RESULT = new Nativo(Integer.parseInt(e), new Tipo(tipoDato.ENTERO), eleft, eright); :}
//        | DECIMAL:e    {: RESULT = new Nativo(Double.parseDouble(e), new Tipo(tipoDato.DECIMAL), eleft, eright); :}
//       | BOOLEANO:e   {: RESULT = new Nativo(Boolean.parseBoolean(e), new Tipo(tipoDato.BOOLEANO), eleft, eright); :}
//        | CADENA:e     {: RESULT = new Nativo(e, new Tipo(tipoDato.CADENA), eleft, eright); :}
//        | CARACTER:e   {: RESULT = new Nativo(e, new Tipo(tipoDato.CARACTER), eleft, eright); :}
//;


TIPO ::= INT      {: RESULT = "int"; :}
       | FLOAT    {: RESULT = "float"; :}
       | BOOL     {: RESULT = "boolean"; :}
       | CHAR     {: RESULT = "char"; :}
       | STRING   {: RESULT = "String"; :}
;

VARIABLE ::= LET ID:id COLON TIPO:t EQ EXPRESION:e     {: RESULT = e; :}
            | CONST ID:id COLON TIPO:t EQ EXPRESION:e  {: RESULT = e; :}
;