 /*
    Siempre se debe definir el paquete
    en el que se encuentra la clase Lexer,
    esto es importante para que el analizador
    lexico pueda encontrar la clase parser.
*/
package com.julian;

// Cup es la clase que contiene los simbolos que
// se usan en el analizador sintactico.
import java_cup.runtime.*;

// Se importa la clase LinkedList para poder usarla en la gramatica.
import java.util.LinkedList;
import com.julian.abstracto.Instruccion;
import com.julian.symbol.*;
import com.julian.exception.Errores;

// Instrucciones
import com.julian.instruction.*;

// Expresiones
import com.julian.expresion.*;


/*
    Codigo del parser, se copia integramente a la clase final.
    Agregamos el manejo de errores.
*/
parser code {:

    // Variable que se usara para almacenar los errores Sintacticos
    public LinkedList<Errores> errors = new LinkedList<Errores>();

    // Funcion de error posiblemente recuperable
    public void syntax_error(Symbol cur_token) {
        //System.out.println("Error de sintaxis en la linea: " + (s.yyline + 1) + " columna: " + (s.yycolumn + 1));
        errors.add(new Errores("Sintactico", " RECUPERABLE Se esperaba: " + cur_token.sym + " se encontro: " + cur_token.value, cur_token.left, cur_token.right));
        System.out.println("Token actual: " + cur_token.value);
        System.out.println("Token esperado: " + cur_token.sym);
        System.out.println("Error recuperable, se intentara recuperar.");
    }

    // Funcion de error No recuperable
    public void unrecovered_syntax_error(Symbol s) {
        // System.out.println("Error de sintaxis en la linea: " + (s.yyline + 1) + " columna: " + (s.yycolumn + 1));
        errors.add(new Errores("Sintactico", "NO RECUPERABLE Se esperaba: " + s.sym + " se encontro: " + s.value, s.left, s.right));
        System.out.println("Token actual: " + cur_token.value);
        System.out.println("Token esperado: " + cur_token.sym);
        System.out.println("Error fatal, no se puede recuperar.");
    }

:}

/*
    El action code funciona como un bloque de codigo que se ejecuta
    antes de que se ejecute la gramatica. En este caso se declara
    una variable de tipo String que se usara para almacenar los
    tokens que se van leyendo.
*/
action code
{:
    String consola = "";
:}

/* ------------Declaracion de simbolos terminales y no terminales---------- */

/* Terminales (tokens obtenidos por el analizador lexico).

   Terminales que no tienen un valor son listados primero, los terminales
   que tienen un valor como los enteros son listados en la segunda o demas
   lineas.
*/

// Terminales que tienen un valor como los enteros son listados
// en la segunda o demas lineas.
terminal String  ID;
terminal String  ENTERO, DECIMAL, BOOLEANO, CADENA, CARACTER;

// Terminales que no tienen un valor son listados primero.
terminal String INT, FLOAT, BOOL, CHAR, STRING;
terminal CAST, LET, CONST, AS;
terminal IF, ELSE, MATCH, DEFAULT;
terminal DO, WHILE, FOR;
terminal BREAK, CONTINUE;
terminal CONSOLE, LOG;
terminal ADD, SUB, MUL, DIV, POW, ROOT, MOD, USUB;
terminal EQ, NE, LT, LE, GT, GE;
terminal ARROW;
terminal OR, AND, NOT;
terminal INCREMENTO, DECREMENTO;
terminal LPAREN, RPAREN, LBRACE, RBRACE, SEMICOLON, COLON, DOT, ASSIGN, COMMA;
terminal STRUCT;
terminal LIST, PUSH, GET, SET, REMOVE, POP, REVERSE;
terminal VOID;
terminal RUN_MAIN;
terminal LBRACKET, RBRACKET;


/* ------------- Sección de no terminales ----------- */

/* No terminales usados en la seccion gramatical.

   Primero se lista los no terminales que tienen un valor Object y despues
   se lista los no terminales que tienen un entero. Un Object se refiere a
   que no tienen tipo, pudiendo ser entero o String.
*/

nonterminal LinkedList<Instruccion> INICIO, INSTRUCCIONES, LISTA_INSTRUCCION;
nonterminal Instruccion INSTRUCCION, IMPRESION, ASIGNACION;
nonterminal Instruccion EXPRESION;
nonterminal Instruccion VALOR;
nonterminal Instruccion VARIABLE;
nonterminal Instruccion CONDICION, CONDIF, CONDELSE, CONDELSEIF;
nonterminal Instruccion SELECCION;
nonterminal LinkedList<Case> CASELIST;
nonterminal Case CASE;
nonterminal DefaultCase DEFAULTCASE;
nonterminal Instruccion TRANSFERENCIA;
nonterminal Instruccion CICLOFOR, ACTUALIZFOR;
nonterminal Instruccion CICLOWHILE, CICLODO;
nonterminal Instruccion CASTEO;
nonterminal Tipo TIPO;

/**
* Simbolos no terminales de la Fase 2
*/
nonterminal LinkedList<Instruccion> INSTRUCCIONES_METODOS;
nonterminal Instruccion INSTRUCCION_METODO;
/* Vectores */
nonterminal Instruccion VECTORES;
nonterminal Instruccion VECTOR;
nonterminal LinkedList<Object> LISTA_VALORES;
nonterminal LinkedList<Object> LISTA_VECTORES;
nonterminal Instruccion ACCESO_VECTOR;
nonterminal Instruccion ASIGNACION_VECTOR;
/* Listas */
nonterminal Instruccion LISTA;
nonterminal Instruccion PUSH_LISTA, GET_LISTA, SET_LISTA;
nonterminal Instruccion REMOVE_LISTA, POP_LISTA, REVERSE_LISTA;
/* Metodo */
nonterminal Instruccion METODO;
nonterminal Instruccion PARAMETRO, LISTA_PARAMETRO;
/* Main */
nonterminal Instruccion MAIN;
/* ------------- Precedencia y Asociatividad de Terminales ----------- */

/*
   La precedencia de los operadores se define aquí.
   Los operadores en las líneas inferiores tienen mayor precedencia
   que los de las líneas superiores.
*/
precedence left     OR;
precedence left     AND;
precedence right    NOT;
precedence left     EQ, NE, LT, LE, GT, GE;
precedence left     ADD, SUB;
precedence left     MUL, DIV, MOD;
precedence nonassoc POW, ROOT;
precedence right    USUB;

/* ------------------- Sección de la gramática ------------------------ */

// Inicia la gramática con el símbolo de inicio.
/* Símbolo de inicio */
start with INICIO;

/* ------------------- Sección de la gramática ------------------------ */
// ESCRIBIR LA GRAMATICA
INICIO ::= LISTA_INSTRUCCION:a         {: RESULT = a; :}
;

LISTA_INSTRUCCION ::= INSTRUCCIONES:a {: RESULT = a; :}
                    | INSTRUCCIONES_METODOS:a {: RESULT = a; :}
;

INSTRUCCIONES ::= INSTRUCCIONES:a INSTRUCCION:b   {: RESULT = a; RESULT.add(b); :}
                | INSTRUCCION:a                   {: RESULT = new LinkedList<Instruccion>(); RESULT.add(a); :}
;

INSTRUCCION ::= IMPRESION:i         SEMICOLON {: RESULT = i; :}
              | VARIABLE:v          SEMICOLON {: RESULT = v; :}
              | ASIGNACION:a        SEMICOLON {: RESULT = a; :}
              | CONDICION:c                   {: RESULT = c; :}
              | SELECCION:s                   {: RESULT = s; :}
              | CICLOWHILE:w                  {: RESULT = w; :}
              | CICLODO:d           SEMICOLON {: RESULT = d; :}
              | CICLOFOR:f                    {: RESULT = f; :}
              | error               SEMICOLON {: RESULT = new instruccionError("Sintactico Error"); :}
;

INSTRUCCIONES_METODOS ::= INSTRUCCIONES_METODOS:a INSTRUCCION_METODO:b   {: RESULT = a; RESULT.add(b); :}
                        | INSTRUCCION_METODO:a                           {: RESULT = new LinkedList<Instruccion>(); RESULT.add(a); :}
;

INSTRUCCION_METODO ::= METODO:m                      {: RESULT = m; :}
                     | VECTORES:d          SEMICOLON {: RESULT = d; :}
                     | ASIGNACION_VECTOR:a SEMICOLON {: RESULT = a; :}
                     | LISTA:l             SEMICOLON {: RESULT = l; :}
                     | PUSH_LISTA:p        SEMICOLON {: RESULT = p; :}
                     | SET_LISTA:s         SEMICOLON {: RESULT = s; :}
;

IMPRESION ::= CONSOLE DOT LOG LPAREN EXPRESION:e RPAREN  {: RESULT = new Print(e, eleft, eright); :}
;

VARIABLE ::=  LET   ID:i COLON TIPO:t ASSIGN EXPRESION:e   {: RESULT = new Declaracion(t, tleft, tright, i, e, 0); :}
            | LET   ID:i COLON TIPO:t                      {: RESULT = new Declaracion(t, tleft, tright, i, 0); :}
            | CONST ID:i COLON TIPO:t ASSIGN EXPRESION:e   {: RESULT = new Declaracion(t, tleft, tright, i, e, 1); :}
            | CONST ID:i COLON TIPO:t                      {: RESULT = new Declaracion(t, tleft, tright, i, 1); :}
;

TIPO ::= INT:t       {: RESULT = new Tipo(tipoDato.ENTERO); :}
       | FLOAT:t     {: RESULT = new Tipo(tipoDato.DECIMAL); :}
       | BOOL:t      {: RESULT = new Tipo(tipoDato.BOOLEANO); :}
       | CHAR:t      {: RESULT = new Tipo(tipoDato.CARACTER); :}
       | STRING:t    {: RESULT = new Tipo(tipoDato.CADENA); :}
       | VOID        {: RESULT = new Tipo(tipoDato.VOID); :}
       | LIST:t      {: RESULT = new Tipo(tipoDato.LISTA); :}
;

ASIGNACION ::= ID:i ASSIGN EXPRESION:e   {: RESULT = new AsignacionVar(i, e, ileft, eright); :}
            | ID:i INCREMENTO            {: RESULT = new Incremento(i, ileft, iright); :}
            | ID:i DECREMENTO            {: RESULT = new Decremento(i, ileft, iright); :}
            | TRANSFERENCIA:t            {: RESULT = t; :}
;

TRANSFERENCIA ::= BREAK:b    {: RESULT = new Break(b, bleft, bright); :}
                | CONTINUE:c {: RESULT = new Continue(c, cleft, cright); :}
;

CONDICION ::= CONDIF:c     {: RESULT = c; :}
            | CONDELSE:c   {: RESULT = c; :}
            | CONDELSEIF:c {: RESULT = c; :}
;

CONDIF ::= IF LPAREN EXPRESION:e RPAREN LBRACE INSTRUCCIONES:i RBRACE {: RESULT = new If(e, i, eleft, eright); :}
;

CONDELSE ::= IF LPAREN EXPRESION:e RPAREN LBRACE INSTRUCCIONES:i RBRACE ELSE LBRACE INSTRUCCIONES:j RBRACE {: RESULT = new Else(e, i, j, eleft, eright); :}
;

CONDELSEIF ::= IF LPAREN EXPRESION:e RPAREN LBRACE INSTRUCCIONES:i RBRACE ELSE CONDICION:c {: RESULT = new IfElseIf(e, i, c, eleft, eright); :}
;

CICLOFOR ::= FOR LPAREN ASIGNACION:a SEMICOLON EXPRESION:e SEMICOLON ACTUALIZFOR:u RPAREN LBRACE INSTRUCCIONES:i RBRACE {: RESULT = new For(a, e, u, i, aleft, iright); :}
;

ACTUALIZFOR ::= ASIGNACION:a {: RESULT = a; :}
;

SELECCION ::= MATCH  EXPRESION:e  LBRACE CASELIST:c DEFAULTCASE:d RBRACE {: RESULT = new Switch(e, c, d, eleft, eright); :}
            | MATCH  EXPRESION:e  LBRACE CASELIST:c RBRACE               {: RESULT = new Switch(e, c, eleft, eright); :}
            | MATCH  EXPRESION:e  LBRACE DEFAULTCASE:d RBRACE            {: RESULT = new Switch(e, d, eleft, eright); :}
;

CASELIST ::= CASELIST:a CASE:b {: RESULT = a; RESULT.add(b); :}
           | CASE:a          {: RESULT = new LinkedList<Case>(); RESULT.add(a); :}
;

CASE ::= EXPRESION:e ARROW LBRACE INSTRUCCIONES:i RBRACE {: RESULT = new Case(e, i, eleft, eright); :}
;

DEFAULTCASE ::= DEFAULT ARROW LBRACE INSTRUCCIONES:i RBRACE   {: RESULT = new DefaultCase(i, ileft, iright); :}
;

CICLOWHILE ::= WHILE LPAREN EXPRESION:e RPAREN LBRACE INSTRUCCIONES:i RBRACE {: RESULT = new While(e, i, eleft, eright); :}
;

CICLODO ::= DO LBRACE INSTRUCCIONES:i RBRACE WHILE LPAREN EXPRESION:e RPAREN {: RESULT = new doWhile(i, e, eleft, eright); :}
;

// public Nativo(Object valor, Tipo tipo, int linea, int columna)
VALOR ::= | ENTERO:e     {: RESULT = new Nativo(Integer.parseInt(e), new Tipo(tipoDato.ENTERO), eleft, eright); :}
          | DECIMAL:e    {: RESULT = new Nativo(Double.parseDouble(e), new Tipo(tipoDato.DECIMAL), eleft, eright); :}
          | BOOLEANO:e   {: RESULT = new Nativo(Boolean.parseBoolean(e), new Tipo(tipoDato.BOOLEANO), eleft, eright); :}
          | CADENA:e     {: RESULT = new Nativo(e, new Tipo(tipoDato.CADENA), eleft, eright); :}
          | CARACTER:e   {: RESULT = new Nativo(e, new Tipo(tipoDato.CARACTER), eleft, eright); :}
;

// public Suma(Instruccion operIzq, Instruccion operDer, int linea, int columna)
EXPRESION ::= SUB EXPRESION:a                 {: RESULT = new Negacion(a, aleft, aright); :}     %prec USUB // La precedencia se aplicara.// La precedencia se aplicara.
            | EXPRESION:a POW  EXPRESION:b    {: RESULT = new Potencia(a, b, aleft, aright); :}  %prec POW
            | EXPRESION:a ROOT EXPRESION:b    {: RESULT = new Raiz(a, b, aleft, aright); :}      %prec ROOT
            | EXPRESION:a MUL  EXPRESION:b    {: RESULT = new Multiplica(a, b, aleft, aright); :}%prec MUL
            | EXPRESION:a DIV  EXPRESION:b    {: RESULT = new Divide(a, b, aleft, aright); :}    %prec DIV
            | EXPRESION:a MOD  EXPRESION:b    {: RESULT = new Modulo(a, b, aleft, aright); :}    %prec MOD
            | EXPRESION:a ADD  EXPRESION:b    {: RESULT = new Suma(a, b, aleft, aright); :}      %prec ADD
            | EXPRESION:a SUB  EXPRESION:b    {: RESULT = new Resta(a, b, aleft, aright); :}     %prec SUB
            | EXPRESION:a EQ   EXPRESION:b    {: RESULT = new Igual(a, b, aleft, aright); :}     %prec EQ
            | EXPRESION:a NE   EXPRESION:b    {: RESULT = new Diferente(a, b, aleft, aright); :} %prec NE
            | EXPRESION:a LT   EXPRESION:b    {: RESULT = new Menor(a, b, aleft, aright); :}     %prec LT
            | EXPRESION:a LE   EXPRESION:b    {: RESULT = new MenorIgual(a, b, aleft, aright); :}%prec LE
            | EXPRESION:a GT   EXPRESION:b    {: RESULT = new Mayor(a, b, aleft, aright); :}     %prec GT
            | EXPRESION:a GE   EXPRESION:b    {: RESULT = new MayorIgual(a, b, aleft, aright); :}%prec GE
            | NOT             EXPRESION:e     {: RESULT = new Not(e, eleft, eright); :}          %prec NOT
            | EXPRESION:a AND EXPRESION:b     {: RESULT = new And(a, b, aleft, aright); :}       %prec AND
            | EXPRESION:a OR  EXPRESION:b     {: RESULT = new Or(a, b, aleft, aright); :}        %prec OR
            | LPAREN EXPRESION:e RPAREN       {: RESULT = e; :}
            | CASTEO:c                        {: RESULT = c; :}
            | VALOR:e                         {: RESULT = e; :}
            | ACCESO_VECTOR:a                 {: RESULT = a; :}
            | GET_LISTA:g                     {: RESULT = g; :}
            | ID:i                            {: RESULT = new AccesoVar(i, ileft, iright); :}
;

CASTEO ::= CAST LPAREN EXPRESION:e AS TIPO:t RPAREN {: RESULT = new Casteo(e, t, eleft, eright); :}
;

/** GRAMATICA FASE 2 */
// ** VECTORES **
// Declaración de vectores
VECTORES ::= LET   ID:i COLON TIPO:t LBRACKET RBRACKET ASSIGN VECTOR:v  {: RESULT = new DeclaracionVector(t, ileft, iright, i, v, 0); :}
           | CONST ID:i COLON TIPO:t LBRACKET RBRACKET ASSIGN VECTOR:v  {: RESULT = new DeclaracionVector(t, ileft, iright, i, v, 1); :}
           | LET   ID:i COLON TIPO:t LBRACKET RBRACKET LBRACKET RBRACKET ASSIGN VECTOR:v  {: RESULT = new DeclaracionVector(t, ileft, iright, i, v, 0); :}
           | CONST ID:i COLON TIPO:t LBRACKET RBRACKET LBRACKET RBRACKET ASSIGN VECTOR:v  {: RESULT = new DeclaracionVector(t, ileft, iright, i, v, 1); :}
;

// Definición de un vector
VECTOR ::= LBRACKET LISTA_VALORES:v RBRACKET  {: RESULT = new Vector(v, vleft, vright); :}
         | LBRACKET LISTA_VECTORES:v RBRACKET {: RESULT = new MultiDimensionalVector(v, vleft, vright); :}
;

// Lista de valores para un vector
LISTA_VALORES ::= LISTA_VALORES:a COMMA VALOR:b {: RESULT = a; RESULT.add(b); :}
                | VALOR:a                       {: RESULT = new LinkedList<Object>(); RESULT.add(a); :}
;

// Lista de vectores para un vector multidimensional
LISTA_VECTORES ::= LISTA_VECTORES:a COMMA VECTOR:b {: RESULT = a; RESULT.add(b); :}
                 | VECTOR:a                        {: RESULT = new LinkedList<Object>(); RESULT.add(a); :}
;

// ** ACCESO A VECTOR **
ACCESO_VECTOR ::= ID:i LBRACKET EXPRESION:e RBRACKET            {: RESULT = new AccesoVector(i, e, ileft, iright); :}
                | ACCESO_VECTOR:a LBRACKET EXPRESION:e RBRACKET {: RESULT = new AccesoVector(a, e, aleft, aright); :}
;

// ** ASIGNACION A VECTOR **
ASIGNACION_VECTOR ::= ID:i LBRACKET EXPRESION:e RBRACKET ASSIGN EXPRESION:v                               {: RESULT = new AsignacionVector(i, e, v, ileft, vright); :}
                    | ID:i LBRACKET EXPRESION:e RBRACKET LBRACKET EXPRESION:p RBRACKET ASSIGN EXPRESION:d {: RESULT = new AsignacionVector(i, e, p, d, ileft, dright); :}
;

// ** LISTAS **
// DECLARACION LISTAS
LISTA ::= LET ID:i COLON TIPO:t LT TIPO:o GT {: RESULT = new DeclaracionLista(i, t, o, ileft, iright); :}
;

// ** PUSH LISTAS **
PUSH_LISTA ::= ID:i DOT PUSH LPAREN EXPRESION:e RPAREN {: RESULT = new PushLista(i, e, ileft, eright); :}
;

// ** GET LISTAS **
GET_LISTA ::= ID:i DOT GET LPAREN EXPRESION:e RPAREN {: RESULT = new GetLista(i, e, ileft, eright); :}
;

//  ** SET LISTAS **
SET_LISTA ::= ID:i DOT SET LPAREN EXPRESION:e COMMA EXPRESION:p RPAREN {: RESULT = new SetLista(i, e, p, ileft, pright); :}
;

// ** REMOVE LISTAS **
REMOVE_LISTA ::= ID:i DOT REMOVE LPAREN EXPRESION:e RPAREN {: RESULT = new RemoveLista(i, e, ileft, eright); :}
;

// ** POP LISTAS **
POP_LISTA ::= ID:i DOT POP LPAREN RPAREN {: RESULT = new PopLista(i, ileft, iright); :}
;

// ** REVERSE LISTAS **
REVERSE_LISTA ::= ID:i DOT REVERSE LPAREN RPAREN {: RESULT = new ReverseLista(i, ileft, iright); :}
;

// ** METODO **
METODO ::= TIPO:t ID:d LPAREN LISTA_PARAMETRO:l RPAREN LBRACE INSTRUCCIONES:i RBRACE  {: RESULT = new Metodo(t, d, l, i, tleft, tright); :}
;

// ** LISTA PARAMETRO **
 LISTA_PARAMETRO ::= LISTA_PARAMETRO:a COMMA PARAMETRO:b {: RESULT = a; RESULT.add(b); :}
                    | PARAMETRO:a                        {: RESULT = new LinkedList<Instruccion>(); RESULT.add(a); :}
;

// ** PARAMETRO **
PARAMETRO ::= ID:i COLON TIPO:t ASSIGN EXPRESION:e {: RESULT = new Declaracion(t, tleft, tright, i, e, 0); :}
            | ID:i COLON TIPO:t                    {: RESULT = new Declaracion(t, tleft, tright, i, 0); :}
;

// ** RUN MAIN **
MAIN ::= RUN_MAIN ID:i LPAREN RPAREN                   {: RESULT = new RunMain(i, ileft, iright); :}
       | RUN_MAIN ID:i LPAREN LISTA_PARAMETRO:l RPAREN {: RESULT = new RunMain(i, l, ileft, iright); :}
;
